server:
  port: 9201
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848/
    gateway:
      discovery:
        locator:
          enabled: true