server:
  port: 9001

spring:
  redis:
    host: 127.0.0.1
    port: 6379
  # 连接端口号
  datasource:
    username: 'root'
    password: 'root'
    url: 'jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8'
    driver-class-name: com.mysql.jdbc.Driver
    devtools:
      restart:
        enabled: true  #设置开启热部署
        additional-paths: src/main/java #重启目录
        exclude: WEB-INF/**
  application:
    name: userModule
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848/
mybatis-plus:
  mapper-locations: classpath:com/example/demo/mapper/xml/*.xml
jwt:
  secret: czq5201314
  expire: 360000
  header: token
redis:
  # Redis数据库索引（默认为0）
  database: 0
  host: localhost
  port: 6379