server:
  port: 9101
spring:
  application:
    name: logModule
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848/
#      config:
#        server-addr: http://localhost:8848/